apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: companyms
  name: companyms
spec:
  containers:
  - image: companyms
    name: concompanyms
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
